### ISSUE TITLE
Doc generation not working

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FsLexYacc#63]
,\build GenerateDocs

gives

```
generate.fsx(25,1): warning FS0211: The search directory 'C:\GitHub\dsyme\FsLexY
acc\docs\tools\../../packages/FSharp.Formatting.2.4.17/lib/net40' could not be f
ound


generate.fsx(26,1): warning FS0211: The search directory 'C:\GitHub\dsyme\FsLexY
acc\docs\tools\../../packages/RazorEngine.3.3.0/lib/net40' could not be found


generate.fsx(27,1): warning FS0211: The search directory 'C:\GitHub\dsyme\FsLexY
acc\docs\tools\../../packages/FSharp.Compiler.Service.0.0.58/lib/net40' could no
t be found

```

**Comment by jackfoxy** [comment]
Just discovered this myself. A PR 8 months ago accepted some enhancements I made to the FsLex.md and they never made it to generated docs.

But I am seeing a different error which suggests a defective template file:

Generating 'index.html'
System.MissingMethodException: Method not found: 'Void System.Web.Razor.Generator.GeneratedClassContext.set_ResolveUrlMethodName(System.String)'.
   at RazorEngine.Compilation.CompilerServiceBase.CreateHost(Type templateType, Type modelType, String className)
   at RazorEngine.Compilation.CompilerServiceBase.GetCodeCompileUnit(String className, String template, ISet`1 namespaceImports, Type templateType, Type modelType) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Compilation\CompilerServiceBase.cs:line 166
   at RazorEngine.Compilation.DirectCompilerServiceBase.Compile(TypeContext context) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Compilation\DirectCompilerServiceBase.cs:line 53
   at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(TypeContext context) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Compilation\DirectCompilerServiceBase.cs:line 102
   at RazorEngine.Templating.TemplateService.CreateTemplateType(String razorTemplate, Type modelType) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 256
   at RazorEngine.Templating.TemplateService.GetTemplate[T](String razorTemplate, Object model, String cacheName) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 374
   at RazorEngine.Templating.TemplateService.GetTemplate(String razorTemplate, Object model, String cacheName) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 352
   at RazorEngine.Templating.TemplateService.Parse(String razorTemplate, Object model, DynamicViewBag viewBag, String cacheName) in c:\_git\RazorEngine\src\Core\RazorEngine.Core\Templating\TemplateService.cs:line 437
   at FSharp.Literate.RazorRender.ProcessFile[a](String source, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 89
   at FSharp.Literate.Templating.generateFile(String contentTag, IEnumerable`1 parameters, FSharpOption`1 templateOpt, String output, IEnumerable`1 layoutRoots) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Formatting.fs:line 79
   at FSharp.Literate.Templating.processFile(LiterateDocument doc, String output, ProcessingContext ctx) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Formatting.fs:line 124
   at FSharp.Literate.Literate.ProcessScriptFile(String input, FSharpOption`1 templateFile, FSharpOption`1 output, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 143
   at <StartupCode$FSharp-Literate>.$Main.processScriptFile@158.Invoke(String file, String output) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 158
   at <StartupCode$FSharp-Literate>.$Main.processDirectory@171(FSharpOption`1 format, FSharpFunc`2 processScriptFile, FSharpFunc`2 processMarkdown, String indir, String outdir) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 189
   at FSharp.Literate.Literate.ProcessDirectory(String inputDirectory, FSharpOption`1 templateFile, FSharpOption`1 outputDirectory, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 171
   at FSI_0002.buildDocumentation() in E:\BitSync\GitRepos\FsLexYacc\docs\tools\generate.fsx:line 84
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in E:\BitSync\GitRepos\FsLexYacc\docs\tools\generate.fsx:line 91
Stopped due to error

**Comment by jackfoxy** [comment]
@dsyme you must be working on a different branch still using "native" Nuget. I just pulled the latest master which is using paket, so version numbers should not be part of the packages path.

I tried changing the doc generate code in build.fsx to look more like what is currently in ProjectScaffold, and got a curious different error. It seems the FakeLib.dll is does not run on Windows! Don't know if this will serve as a clue:

Error:
System.Exception: Start of process E:\BitSync\GitRepos\FsLexYacc\packages\FAKE\tools\FakeLib.dll failed. The specified executable is not a valid application for this OS platform.
   at Fake.ProcessHelper.ExecProcessWithLambdas@87-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 87
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 87
   at FSI_0005.Build.executeFAKEWithOutput(String workingDirectory, String script, String fsiargs, IEnumerable`1 envArgs) in E:\BitSync\GitRepos\FsLexYacc\build.fsx:line 147
   at FSI_0005.Build.buildDocumentationTarget(String fsiargs, String target) in E:\BitSync\GitRepos\FsLexYacc\build.fsx:line 157
   at FSI_0005.Build.clo@165-12.Invoke(Unit _arg1) in E:\BitSync\GitRepos\FsLexYacc\build.fsx:line 166
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

**Comment by sergey-tihon** [comment]
@jackfoxy please check that your changes are published

**Comment by jackfoxy** [comment]
@sergey-tihon yes, thanks. Does build GenerateDocs work now?

**Comment by sergey-tihon** [comment]
Yes,
